project_booking_homepage:
    path:     /
    defaults: { _controller: ProjectBookingBundle:Form:index }

project_booking_ticket:
    path: /reserver
    defaults: { _controller: ProjectBookingBundle:Form:ticket } 

project_booking_command:
    path: /ajout_des_informations
    defaults: { _controller: ProjectBookingBundle:Form:command }

project_booking_payment:
    path: /payer
    defaults: { _controller: ProjectBookingBundle:Form:payment }