project_booking_homepage:
    path:     /
    defaults: { _controller: ProjectBookingBundle:Form:index }

project_booking_form:
    path: /reserver
    defaults: { _controller: ProjectBookingBundle:Form:booking }

project_booking_visitors:
    path: /reservation
    defaults: { _controller: ProjectBookingBundle:Form:addVisitors }