<?php

namespace Project\BookingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    public function findTotalTicketsByDayToVisit($dayToVisit)
    {
        $queryBuilder = $this->createQueryBuilder('b')
            ->select('SUM(b.nbTickets)')
            ->where('b.dayToVisit = :day')
            ->setParameter('day', $dayToVisit);

        $query = $queryBuilder->getQuery();

        return $query->getSingleScalarResult();
    }
}
