<?php

namespace Project\BookingBundle\Repository;

/**
 * FormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNbTickets()
	{
	/*	$qb = $this->createQueryBuilder('t');
		$qb->select('COUNT(\'nbTickets\')');

		return $qb->getQuery()->getSingleScalarResult();*/
	}

	public function getNbTicketsSold($dayToVisit)
	{
		/*$query = $this->_em->createQuery('SELECT t.nbTickets FROM ProjectBookingBundle:Booking t WHERE t.dayToVisit = :dayToVisit');

		$query->setParameter('dayToVisit', $dayToVisit);

		$results = $query->getResult();

		return $results;*/
	}
}
