<?php

namespace Project\BookingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends EntityRepository
{
    public function findBirthday($birthday)
    {
        $qb = $this->createQueryBuilder('v');

        $qb->where('v.birthday = :birthday')
            ->setParameter('birthday', $birthday);

        return $qb->getQuery()->getResult();
    }

}
